'use client';

/**
 * D061 / P056.2.10 — Primitive Demo Page (Wave 1A · gallery before composition).
 *
 * Renders every Wave-1 primitive together with real sample data so UI / RTL /
 * contrast / theme issues surface at the cheapest fix point — BEFORE Home/Inbox
 * compose them. Reuses the P056.1 ThemeProvider for the EN ⇄ HE (LTR/RTL) and
 * Operate ⇄ Build toggles, on the canonical `.ds-surface` light theme.
 *
 * Gate (CTO re-validates in Chrome): all primitives render · RTL EN+HE · WCAG-AA
 * (color+icon+text) · theme consistent. This is a verification surface, not a
 * CEO screen.
 */

import { useState } from 'react';
import { useTheme } from '../../../components/theme-provider';
import {
  AIChiefOfStaffPanel,
  ActionButton,
  ActivityFeed,
  DataTag,
  DecisionCard,
  ProjectCard,
  RecommendationCard,
  RiskCard,
  SearchBar,
  StatusBadge,
  type ActivityItem,
} from '../../../components/ds';

const COPY = {
  en: {
    heading: 'Component Library · Wave 1A Primitives',
    tagline: 'Every primitive on real sample data — gallery before composition.',
    briefingHeadline: 'Two decisions need you this morning.',
    briefingSummary:
      'The North Star pipeline is healthy and shipping. One critical risk in auth latency needs a call, and a proposed Q4 push is waiting on your approval. Everything else is green.',
    decisionTitle: 'Approve the Q4 marketing budget reallocation',
    decisionDesc:
      'Shift $40k from paid social to lifecycle email after the funnel analysis showed a 3.2× ROI gap. Reversible next quarter.',
    proposalTitle: 'Spin up a dedicated incident-response runbook',
    recoTitle: 'Cut auth p99 latency before it breaches SLA',
    recoSummary:
      'CTO recommends moving session validation to the edge cache. Three prior incidents trace to the same cold path; the change is isolated and reversible.',
    riskDesc: 'Auth service p99 latency is trending toward the 800ms SLA breach under peak load.',
    riskDesc2: 'Single connector credential rotation is manual and undocumented.',
    sectionLabels: {
      briefing: 'AI Chief of Staff Panel (foundation-tier)',
      decisions: 'Decision Cards',
      recos: 'Recommendation Cards',
      risks: 'Risk Cards',
      projects: 'Project Cards',
      atoms: 'Atoms · StatusBadge · DataTag · ActionButton',
      feed: 'Activity Feed (lazy)',
      search: 'Search Bar (shell)',
    },
  },
  he: {
    heading: 'ספריית רכיבים · פרימיטיבים גל 1A',
    tagline: 'כל רכיב על נתוני דוגמה אמיתיים — גלריה לפני הרכבה.',
    briefingHeadline: 'שתי החלטות מחכות לך הבוקר.',
    briefingSummary:
      'צינור יעד-העל תקין ומשגר. סיכון קריטי אחד בזמן תגובת האימות דורש החלטה, ודחיפת רבעון רביעי מוצעת ממתינה לאישורך. כל השאר ירוק.',
    decisionTitle: 'אישור הקצאה מחדש של תקציב השיווק לרבעון הרביעי',
    decisionDesc:
      'העברת 40 אלף דולר ממדיה חברתית בתשלום לדוא"ל מחזור-חיים לאחר שניתוח המשפך הראה פער החזר השקעה של פי 3.2. הפיך ברבעון הבא.',
    proposalTitle: 'הקמת ספר נהלים ייעודי לתגובה לתקריות',
    recoTitle: 'הפחתת זמן תגובת האימות לפני חריגה מה-SLA',
    recoSummary:
      'סמנכ"ל הטכנולוגיה ממליץ להעביר את אימות הסשן למטמון הקצה. שלוש תקריות קודמות מקורן באותו נתיב קר; השינוי מבודד והפיך.',
    riskDesc: 'זמן תגובת האימות מתקרב לחריגת ה-SLA של 800 מ"ש בעומס שיא.',
    riskDesc2: 'סבב אישורי הגישה של מחבר יחיד הוא ידני ולא מתועד.',
    sectionLabels: {
      briefing: 'פאנל ראש המטה הבינה המלאכותית (שכבת יסוד)',
      decisions: 'כרטיסי החלטה',
      recos: 'כרטיסי המלצה',
      risks: 'כרטיסי סיכון',
      projects: 'כרטיסי פרויקט',
      atoms: 'אטומים · תג סטטוס · תג נתונים · כפתור פעולה',
      feed: 'הזנת פעילות (עצלה)',
      search: 'שורת חיפוש (מעטפת)',
    },
  },
} as const;

export default function PrimitivesDemoPage() {
  const { locale, dir, setLocale, mode, toggleMode } = useTheme();
  const t = COPY[locale];
  const [busyDemo, setBusyDemo] = useState(false);

  const feedItems: ActivityItem[] = [
    { id: 'a1', kind: 'Decision', label: 'CEO approved the lifecycle-email reallocation.', at: '2026-06-08T09:12:00Z', context: 'North Star' },
    { id: 'a2', kind: 'Risk', label: 'Auth p99 latency risk re-detected (×3).', at: '2026-06-08T08:40:00Z', health: 'action' },
    { id: 'a3', kind: 'Outcome', label: 'Signups +18% week-over-week recorded.', at: '2026-06-07T22:05:00Z', health: 'healthy' },
    { id: 'a4', kind: 'Directive', label: 'CTO directive: edge-cache session validation.', at: '2026-06-07T17:30:00Z' },
    { id: 'a5', kind: 'Report', label: 'Daily briefing generated by Chief of Staff.', at: '2026-06-07T06:00:00Z' },
    { id: 'a6', kind: 'Proposal', label: 'Incident-response runbook proposed.', at: '2026-06-06T15:20:00Z' },
    { id: 'a7', kind: 'Evidence', label: '4 evidence tokens attached to task #214.', at: '2026-06-06T11:00:00Z' },
  ];

  const noop = () => {};

  return (
    <div className="ds-surface min-h-screen px-md py-lg sm:px-lg" dir={dir}>
      <div className="mx-auto max-w-5xl">
        <header className="mb-xl flex flex-wrap items-end justify-between gap-md">
          <div>
            <h1 className="font-display text-display text-on-surface">{t.heading}</h1>
            <p className="mt-xs font-body-lg text-body-lg text-on-surface-variant">{t.tagline}</p>
            <p className="mt-xs font-label-sm text-label-sm uppercase text-outline">
              dir={dir} · locale={locale} · mode={mode}
            </p>
          </div>
          <div className="flex items-center gap-sm">
            <ActionButton variant="primary" onClick={() => setLocale(locale === 'en' ? 'he' : 'en')}>
              {locale === 'en' ? 'עברית (RTL)' : 'English (LTR)'}
            </ActionButton>
            <ActionButton variant="secondary" onClick={toggleMode}>
              {mode === 'operate' ? 'Switch to Build' : 'Switch to Operate'}
            </ActionButton>
          </div>
        </header>

        {/* AIChiefOfStaffPanel — composite, embeds the most-urgent DecisionCard */}
        <Section title={t.sectionLabels.briefing}>
          <AIChiefOfStaffPanel
            headline={t.briefingHeadline}
            summary={t.briefingSummary}
            generatedAt="2026-06-08 09:15 UTC"
            signals={[
              { state: 'action', text: '1 critical risk' },
              { state: 'attention', text: '2 decisions waiting' },
              { state: 'healthy', text: '5 projects healthy' },
            ]}
            metrics={[
              { label: 'Decisions', value: 2 },
              { label: 'Open risks', value: 3 },
              { label: 'Projects', value: 6 },
              { label: 'Wins (7d)', value: 11 },
            ]}
          >
            <DecisionCard
              title={t.decisionTitle}
              description={t.decisionDesc}
              priority="P1"
              status="proposed"
              dueDate="2026-06-10"
              onApprove={noop}
              onReject={noop}
              onClarify={noop}
            />
          </AIChiefOfStaffPanel>
        </Section>

        {/* Decision cards — read-only, actionable, busy */}
        <Section title={t.sectionLabels.decisions}>
          <div className="grid gap-lg lg:grid-cols-2">
            <DecisionCard title={t.decisionTitle} description={t.decisionDesc} priority="P0" status="proposed" dueDate="2026-06-10" />
            <DecisionCard
              title={t.proposalTitle}
              source="proposal"
              priority="P2"
              status="proposed"
              onApprove={() => setBusyDemo((b) => !b)}
              onReject={noop}
              onClarify={noop}
              busy={busyDemo ? 'approve' : null}
            />
          </div>
        </Section>

        {/* Recommendation cards — Wave-1 reality (no metrics) + back-filled slot */}
        <Section title={t.sectionLabels.recos}>
          <div className="grid gap-lg lg:grid-cols-2">
            <RecommendationCard
              executiveName={locale === 'en' ? 'Chief Technology Officer' : 'סמנכ"ל טכנולוגיה'}
              title={t.recoTitle}
              summary={t.recoSummary}
              evidenceCount={3}
              onAccept={noop}
              onDismiss={noop}
            />
            <RecommendationCard
              executiveName={locale === 'en' ? 'Chief Financial Officer' : 'סמנכ"ל כספים'}
              title={t.decisionTitle}
              summary={t.decisionDesc}
              evidenceCount={1}
              confidence={0.82}
              historicalRoi="3.2×"
              onAccept={noop}
            />
          </div>
        </Section>

        {/* Risk cards — full severity spread maps to the triad */}
        <Section title={t.sectionLabels.risks}>
          <div className="grid gap-lg lg:grid-cols-2">
            <RiskCard description={t.riskDesc} severity="critical" status="open" recordedBy="executive:cto" context="North Star" generation={3} onMitigate={noop} />
            <RiskCard description={t.riskDesc2} severity="high" status="open" recordedBy="executive:coo" context="Platform" />
            <RiskCard description="Marketing attribution drifts beyond the 5% tolerance band." severity="medium" status="monitoring" recordedBy="executive:vp-marketing" />
            <RiskCard description="Docs site has three stale runbook links." severity="low" status="open" recordedBy="executive:chief-of-staff" />
          </div>
        </Section>

        {/* Project cards — all four health states incl. null "no signal" */}
        <Section title={t.sectionLabels.projects}>
          <div className="grid gap-lg sm:grid-cols-2 lg:grid-cols-3">
            <ProjectCard name="North Star" slug="north-star" description="Flagship growth funnel." lifecycle="active" health="healthy" healthLabel="Healthy: System Core" openRecommendations={0} />
            <ProjectCard name="Q4 Pipeline" slug="q4-pipeline" description="Seasonal revenue push." lifecycle="active" health="attention" bottleneck="Checkout conversion" openRecommendations={2} />
            <ProjectCard name="Auth Platform" slug="auth-platform" description="Shared identity service." lifecycle="active" health="action" bottleneck="p99 latency" openRecommendations={4} />
            <ProjectCard name="Research Sandbox" slug="research-sandbox" description="No portfolio snapshot yet." lifecycle="inactive" health="neutral" openRecommendations={0} />
          </div>
        </Section>

        {/* Atoms */}
        <Section title={t.sectionLabels.atoms}>
          <div className="space-y-lg">
            <div className="flex flex-wrap gap-sm">
              <StatusBadge state="healthy" />
              <StatusBadge state="attention" />
              <StatusBadge state="action" />
              <StatusBadge state="neutral" />
            </div>
            <div className="flex flex-wrap gap-sm">
              <DataTag kind="HAVE" />
              <DataTag kind="DERIVED" />
              <DataTag kind="NEW FIELD" />
              <DataTag kind="NEW SERVICE" />
            </div>
            <div className="flex flex-wrap items-center gap-sm">
              <ActionButton variant="primary" onClick={noop}>Primary</ActionButton>
              <ActionButton variant="secondary" onClick={noop}>Secondary</ActionButton>
              <ActionButton variant="ghost" onClick={noop}>Ghost</ActionButton>
              <ActionButton variant="primary" busy onClick={noop}>Working</ActionButton>
              <ActionButton variant="primary" disabled onClick={noop}>Disabled</ActionButton>
            </div>
          </div>
        </Section>

        {/* Activity feed */}
        <Section title={t.sectionLabels.feed}>
          <div className="rounded-lg border border-outline-variant bg-surface-container-lowest p-lg">
            <ActivityFeed items={feedItems} pageSize={4} />
          </div>
        </Section>

        {/* Search bar shell */}
        <Section title={t.sectionLabels.search}>
          <SearchBar onSubmit={noop} />
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-xl">
      <h2 className="mb-md font-headline-md text-headline-md text-on-surface">{title}</h2>
      {children}
    </section>
  );
}
